### PR TITLE
OPENEUROPA-559

### PR DESCRIPTION
**Pull request by imanoleguskiza**
### Description

Add multilingual configuration to existing paragraphs

### Changelog

- Added: Add multilingual configuration to existing paragraphs
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### CODE REVIEW

**Comment by richardcanoe** [comment]
I agree with @ademarco that we should test these translations. This means we will probably need to enter more config to this branch, since there are missing dependent modules and languages necessary for the translation tasks themselves.

**Comment by imanoleguskiza** [comment]
Hi all,
thanks for your comments. Regarding testing this changes, I had a lengthy conversation with @ademarco and @pfrenssen about it, as well as investing a lot of time trying to figure out the best way to do it.
In the end, because of comments by @pfrenssen arguing against testing configuration and because of the sheer complexity to test it, I decided to not add tests.
If you believe this are mandatory, I would appreciate if you had any suggestions as to how to do them :(

**Comment by pfrenssen** [comment]
I agree that this doesn't need tests, for the following reasons:

1. The ticket is not a user story but a technical task. Since it is not a user story we don't need a Behat test because end user behaviour has not been defined. There are no acceptance criteria in the ticket that say "Given I am logged in as a translator, and I go to this page, then I am able to translate this content".
2. There is no code being written, so we don't need unit tests.
3. Since this PR consists of purely configuration, we can trust that is already covered by tests in the relevant core and contrib modules.

I can understand that people might be concerned with regressions if this configuration would change, but without a clearly defined user story this is pointless and subject to change anyway. In the future there will certainly be user stories that deal with translation, and that is the right moment to provide these tests.

**Comment by brummbar** [comment]
I agree with @pfrenssen comment. As soon as we have user stories that require translations of content, we will write tests that will assure that the configuration won't change.

**Comment by brummbar** [comment]
The rich text paragraph type doesn't have its text field marked as translatable. The remaining fields work good.

**Pull request merged**
